[package]
name = "bitonic_sorter"
version = "0.1.0"
authors = ["kozo yamagata <tune002@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.3"
rand_pcg = "0.3.0"
